// Astro virtual modules type declarations
// These modules are generated by Astro at build/dev time
// Fallback declarations for when .astro/types.d.ts doesn't exist

declare module 'astro:content' {
  export { z } from 'astro/zod'

  export type CollectionEntry<C extends string> = any

  export type CollectionKey = any

  export type ContentCollectionKey = any

  export type DataCollectionKey = any

  export function getCollection<C extends string>(collection: C): Promise<any[]>

  export function getEntry<C extends string, E extends string>(
    collection: C,
    entryId: E,
  ): Promise<any>

  export function getEntries<C extends string>(
    entries: { collection: C; id: string }[],
  ): Promise<any[]>

  export function reference<C extends string>(collection: C): any
}
