const dirtyAppIds = [
  // apps where IAPs could potentially work
  "com.MYOStudito.AutoChessRPG&hl=en&gl=US",
  "com.sparklingsociety.battleempireromanwars&hl=en&gl=US",
  "manastorm.spacehorse&hl=en&gl=US",
  "com.exaltedstudio.bighelmetheroes&hl=en&gl=US",
  "com.kongregate.mobile.cardinalquest.google",
  "com.aanz.ludo.online.multiplayer.offlineludo&hl=en&gl=US",
  "com.funload.killmonster&hl=en&gl=US",
  "com.OpenWorldInteractive.ClickerWarriors",
  "com.chillgaming.combatquest",
  "com.notdoppler.crashofcars",
  "com.animocabrands.google.CrazyKings",
  "com.dark.heroes",
  "com.alicegames.idle.rpg.battler",
  "com.Roika.Darkrise",
  "com.survival.last&hl=en_US&gl=US",
  "com.loongcheer.tcg.deckadventure",
  "space.indiecatsoft.mercenaryx&hl=en_US&gl=US",
  "com.dejavustudio.AnotherWorld",
  "com.YEMA.FinalDestiny",
  "com.aegisinteractive.goo&hl=en_US&gl=US",
  "com.BerryBaby.skullking",
  "com.BaronnerieGames.Guildmasters&hl=en&gl=US",
  "com.prty.hpz&hl=en&gl=US",
  "com.hariotica&hl=en_US&gl=US",
  "com.moondustries.idlefamily",
  "com.gaminho.idlefivebasketball&hl=en&gl=US",
  "com.aerilys.idle.grail&hl=en_US&gl=US",
  "com.idle.hamster.energy",
  "com.IdleMagicSchool.jlyt&hl=en&gl=US",
  "com.chargedmonkey.idlequestheroesepicdungeonrpg",
  "com.hadeul.mage",
  "com.lemonjamgames.idlehero",
  "com.lemonjamstudio.infiniteknights&hl=en&gl=US",
  "com.lemonjamgames.worldtale",
  "com.wb.goog.injustice&hl=en_US&gl=US",
  "com.alohagamestudios.kingofheroes&hl=en&gl=US",
  "com.nijigames.leturn",
  "com.llgroup.linearquestbattleidlerpg&hl=en&gl=US",
  "kemco.rideonjapan.mareniabar",
  "com.d3p.mpq&hl=en&gl=US",
  "com.guycorp.rpg.games.idle.merge.games",
  "com.booda.medieval.rpg",
  "com.dreamplay.messyrc.google&hl=en_GB&gl=US",
  "com.MythiKiwi.MoeOS",
  "com.dungeon.rpg.freeherowars",
  "com.hyperdotstudios.mythiclegends&hl=en&gl=US",
  "com.lemonjamgames.neonimpact",
  "com.brightstripe.parcels",
  "path.of.evil.immortal.hunter.dungeon.rpg&hl=en&gl=US",
  "com.notebuddy.punchman&hl=en&gl=US",
  "com.tiregamestudio.rcp.real.car.parking&hl=en&gl=US",
  "net.hexage.reaper&hl=en&gl=US",
  "vn.apero.warriorDefenders.td.tower.defense.rush",
  "com.ForgeGames.ShadowOfTheEmpire&hl=en&gl=US",
  "com.kiloo.smashchamps&hl=en&gl=US",
  "com.oddyarts.StoneOfLifeEXNative&hl=en&gl=US",
  "com.SimpleMission.SwordofOath&hl=en&gl=US",
  "com.wannaplay.talesofdust",
  "com.metagamestudio.tapbusters",
  "com.sixmonkeys.tap.hero.idle.rpg.game",
  "com.generagames.tap.pirates.idle&hl=en&gl=US",
  "com.loongcheer.moke.pixelknight.idlerpg.adventure",
  "com.excellcube.ultimateaxeclicker&hl=en&gl=US",
  "com.vpnmasterx.pro",
  "com.stereo7games.wwd",
  "com.malcs.melvoridle",
  "ninja.creed.sniper.real3d.action.free.android&gl=US",
  "com.studiowildcard.wardrumstudios.ark&hl=en_US&gl=US",
  "com.squareenixmontreal.hitmansniperandroid",
];

const cleanAppIds = dirtyAppIds.map((i) => i.split("&")[0]);

const result = {};

for (const id in cleanAppIds) {
  result[cleanAppIds[id]] = {
    category: "unclear-iap",
    features: ["unclear-iap"],
  };
}

console.log(result);
