import gplay from "google-play-scraper";

const appNames = [
  "Arcane Quest Legends",
  "Ark Survival Evolved",
  "Art Inc",
  "Asdivine hearts 2",
  "Back Wars",
  "Batman-The telltale series",
  "Battle Camp (maybe?)",
  "Battle Empire: Roman Wars",
  "Beat The Boss(3)",
  "Bejeweled Blitz ",
  "Bid Wars: Pawn Empire",
  "Big Hunter",
  "Bio Inc",
  "Biotix ",
  "Biotix 2",
  "Bitcoin Billionaire",
  "Blockheads",
  "Blocky Roads",
  "Bloodcopter",
  "Bloons Adventure time",
  "Bounzy",
  "Bowmasters",
  "Brawls of steel",
  "Brew Town",
  "Bridge Race",
  "Bubble Empire",
  "Business strategy",
  "Card Thief",
  "Cardinal Quest 2",
  "Car industry Tycoon ",
  "Carpet bombing - Fighter Bomber Attack",
  "Cartoon999",
  "Cartoon Wars",
  "Cartoon Wars 2",
  "CarX Drift Racing 2",
  "Castle Cats",
  "Castle Fusion",
  "Catan Universe ",
  "Cat Game",
  "Cat Shooting War",
  "Cells to Singularity",
  "Chess Universe",
  "Chicken Gun",
  "Chief Follow",
  "Chimpact 2 Family Tree",
  "CivCrafter",
  "Clusterduck",
  "Colonize: Transport Tycoon ",
  "Construction City 2",
  "Cookie Jam",
  "Cookies Inc",
  "Cookies TD",
  "Corginaut",
  "Corin",
  "Coverfire",
  "Craft Island",
  "Crafty town Merge city",
  "Crashlands: story driven crafting arpg",
  "Crossy road",
  "Cut The Rope",
  "Cut it (Phoenix global)",
  "Dark corridors 2",
  "Dashero: Archer sword 3D",
  "Dead Colony",
  "Dead Shell Roughlike RPG",
  "Death Tycoon",
  "DeckEleven's Railroads 2",
  "Deep Town",
  "Defender 1",
  "Desertopia",
  "Designer City",
  "Devils and demons - arena wars",
  "Devtycoon 2",
  "Dictator 2",
  "Digfender",
  "Dig Out! - Gold Digger Adventure",
  "Disney Emoji Blitz",
  "Don't get fired",
  "Down Detector",
  "Dragon Hills",
  "Dragon Hills 2",
  "Dragon Village",
  "DragonVale",
  "Draw a Stickman: EPIC 2",
  "Drawing Cartoons 2",
  "Dreaming dimension ",
  "Drum Pads 24 - Music Maker",
  "Dungeon999",
  "Dungeon Shop Tycoon",
  "Duolingo",
  "Dusk Wood",
  "Duskwood:Crime",
  "Dustoff heli rescue 2",
  "Egg Inc",
  "EgoSword",
  "Endless Quest: Hades Blade",
  "Endurance",
  "Eon music player",
  "Epic Battle Sim 1",
  "Epic Battle Sim 2",
  "Epic Conquest",
  "Epic Game Maker - Create and Share Your Levels!",
  "Epic Raft",
  "Epic magic warrior",
  "European war 4: napoleon",
  "Event Horizon ",
  "Evermerge",
  "Evolution Galaxy",
  "Exiled Kingdoms",
  "ExoMiner - Idle Miner Adventure  ",
  "Extra Lives",
  "Fallout Shelter",
  "Fancade",
  "Fantasy Forge",
  "Family Guy- Another Freakin' Mobile Game",
  "Faraway: Tropic Escape",
  "FAU-G: Fearless and United Guards",
  "Fight Club 5 Edition",
  "Fishing life",
  "Fish match - home design ",
  "Flappy Crush",
  "Fleet Combat",
  "Fleet Combat 2",
  "Flow Free",
  "Force Rotation",
  "FX Master",
  "Gacha Club",
  "Gacha Resort",
  "Gacha World",
  "Galaxy on Fire(2)",
  "Galaxy Reaver",
  "Chef Emma",
  "Godus",
  "Grim Quest - Old School RPG",
  "Grimvalor ",
  "Grim Wandering",
  "Grow Swordmaster",
  "Guncat (cat shooting war)",
  "GunClub 3: Virtual Weapon Sim",
  "Gun Crafter",
  "Guns and spurs 2 ",
  "Guns n glory heroes ",
  "Headhunters.io",
  "Head basketball ",
  "Head Soccer ",
  "Heads up!",
  "Hero Z ",
  "Hey Girl",
  "High heels",
  "Hill Climb Racing 1",
  "Hills of Steel 2",
  "Hitman Sniper",
  "Homunculus Sandbox",
  "Hoplite",
  "Hotel Slime ",
  "Hotel Tycoon Empire - Idle Manager Simulator Games",
  "Hungry Shark World",
  "Idle Brick Breaker",
  "Idle Cafe",
  "Idle City Empire",
  "Idle Construction 3D",
  "Idle Crafting",
  "Idle Crafting Empire",
  "Idle Dice",
  "Idle Fish Inc",
  "Idle Human",
  "Idle Mafia",
  "Idle Oil Tycoon: Gas Factory Simulator ",
  "Idle Planet Miner",
  "Idle robot ",
  "Idle Skilling - Pocket RPG Tycoon",
  "Idle Slayer",
  "Idle Space Farm(er)",
  "Illuminati Adventure Incremental",
  "Impossible Space",
  "Infectinator",
  "Infectinator 3",
  "Injustice: Gods among us",
  "Inshot Video",
  "Interstellar pilot",
  "Into the dead 1",
  "Investigation Detective Story",
  "Iron marines",
  "Jalup (Learn Japanese)",
  "Jelly Fill",
  "Jetpack Joyride",
  "Jobmania Eternal Dungeon",
  "Johnny Trigger",
  "Jurassic World",
  "Kick The Buddy",
  "Kick The Buddy",
  "Kinemaster (root)",
  "Kingdom Rush",
  "Kingdom Rush origins ",
  "Kingdom Rush Vengeance",
  "Knife Hit",
  "Labyrinth Legend ",
  "Labyrinth of The Witch",
  "Lapse: A forgoten future",
  "Last hope TD",
  "LegionWar",
  "Lego Batman 3",
  "Lego Marvel Superheroes",
  "Lego Star Wars The Force Awakens",
  "Let's Survive",
  "Leturn-Defense of Magic",
  "Life gallery. Creepy one",
  "Lil Alchemist",
  "Lily's garden ",
  "Ling App: Learn Languages (60+)",
  "Lonewolf a sniper story",
  "Magic touch: wizard for hire",
  "Make It Rain God Sweep The Queen",
  "Make More",
  "Marvel Puzzle Quest",
  "Match land",
  "Mekorama",
  "Melon Clicker",
  "Memes Wars",
  "Merchant",
  "Merge Camp elves and fairies",
  "Merge Dragons",
  "Merge Farm",
  "Merge Friends",
  "Merge Magic",
  "Merge Master",
  "Merge Mermaids",
  "Merge Monsters",
  "Merge Safari",
  "Michonne",
  "Miner gun builder",
  "Mirror Lab",
  "MMX Hill Dash 2",
  "Modern Age: President Simulator ",
  "Modern warplanes: sky fighters pvp",
  "Moons Closet",
  "Moonshades",
  "Motor World Car Factory",
  "Mr. Bullet",
  "Mr. Gun",
  "Musecore",
  "My Factory Tycoon",
  "Mystic Guardian",
  "Neko atsume: kitty collector ",
  "Neko Gacha",
  "Necromancer by prismathunder",
  "Necromancy",
  "Neighbors from hell 1",
  "Neighbors from hell 2",
  "NeverGone",
  "Ninja Arashi ",
  "Ninja Arash 2 ",
  "Ninja dash",
  "Ninja’s Creed: 3D Sniper Shooting Assassin Game  ",
  "Ninja Turtles: Legends ",
  "Noblemen 1896",
  "No Humanity",
  "NYX Music Player",
  "Ocean is Home",
  "Ocean is Home 2",
  "OceanHorn",
  "Oh My Office",
  "OneBit Adventure ",
  "On my own (root?)",
  "Otherworld Legends",
  "Own Kingdom (root?)",
  "Paint by number - relax",
  "Party Clicker",
  "Pascal's Wager",
  "Payback 2",
  "Pewdiepies tuber simulator",
  "Phantom Rose Scarlet",
  "Phonograph music player",
  "Pirates and Traders",
  "Pirates evolution",
  "Pirate Outlaws",
  "Pixel Car Racer",
  "Plague Inc",
  "Play magnus ",
  "Plants vs Zombies Free",
  "Play (puzzle game)",
  "Pocket Build",
  "Pocket mortys",
  "Pocket trains",
  "Pocket World Island of Adventure",
  "Polyescape 1",
  "Polyescape 2",
  "Portal Knights ",
  "Pou",
  "Producer: choose your star",
  "Progressbar95",
  "Project: Muse ",
  "Psiphon pro",
  "Psych!",
  "Pudding Monsters",
  "Quadropus rampage",
  "Raft Survival Ocean nomad. ",
  "Reactor idle manager",
  "Rebel Inc",
  "Red dead companion ",
  "Retro bowl",
  "Rise of Burk",
  "Rival Stars Basketball",
  "Rodeo stampede",
  "RTS Siege Up! - Medieval Warfare Strategy Offline  ",
  "Run and gun: banditos ",
  "Run bird run",
  "Rune Rebirth",
  "Sand:box by SmellyMoo",
  "SAS4",
  "Sea Merge",
  "Second world War online strategy game",
  "Secret cat forest",
  "Shadow fighter 2: Shadow & ninja fighting games  ",
  "Shopkins Run",
  "Sierra 7",
  "Simplest RPG game",
  "Simpsons tapped out",
  "Sky Dancer",
  "Slice & dice",
  "Slug it Out 2",
  "Smash Bandits Racing",
  "Smash Heat",
  "Smashy Road",
  "Smashy Road 2",
  "Snake Blast!",
  "Soccer Royale",
  "Solitaire: Decked out",
  "Sonic Dash 2",
  "Space agency",
  "Space Marshalls 2",
  "Spartan Firefight",
  "Special Ops: FPS PvP War-Online gun shooting games",
  "SpongeBob Krusty Cook-Off",
  "Steampunk defence",
  "Steampunk Idle Spinner ",
  "Stellar Wanderer",
  "Stellio music and mp3 player",
  "Stickman Dragon Fight - Super Stick Warriors",
  "Stickman Hook",
  "Stickman Master Archer",
  "Stick Squad: Sniper Battlegrounds ",
  "Stick war legacy ",
  "Stick with it",
  "Stone Park Tycoon",
  "Stormblades ",
  "Strange world",
  "Subdivision Infinity 3D shooter",
  "Summoners Greed",
  "Super City",
  "Super Fowlst",
  "Survival Ark",
  "Swamp attack",
  "Sword and glory",
  "Swordigo ",
  "Swords and Sandals 2",
  "Swords and Sandals 5",
  "Tabletop racing premium ",
  "Takashi Ninja",
  "Talisman digital edition",
  "Talking Angela ",
  "Tank Block Blast",
  "Tank ON jeep hunter",
  "Tank Stars",
  "Tap Craft",
  "Tap Tap Breaking",
  "Tap Wizard",
  "Tap to Riches",
  "Tapbusters",
  "Tavern Rumble",
  "Terrarium",
  "The Agent from C.O.G.O.O. (Minesweeper)",
  "The Bonfire",
  "The Dark",
  "Theotown",
  "The parallax ",
  "The Trail",
  "The tribes beta",
  "The Wanderer",
  "They Are Coming: Zombie Shooting & Defense",
  "Timing Hero",
  "Tiny Rails",
  "Tiny Room",
  "Tiny Shop: Idle Fantasy ",
  "Tiny Space Program",
  "TMNT ",
  "Tomb of the mask",
  "Towelfight 2",
  "Tower Breaker",
  "Tower Madness 2",
  "Townsmen",
  "Town Stories! ",
  "Trap Dungeons",
  "Tricky Castle ",
  "Triple Agent",
  "Troll Patrol",
  "Trucker Joe",
  "Tunnelbear VPN",
  "Turbo Dismount",
  "Ultimate Dragon Master",
  "Vampires Fall: Origins",
  "Video game tycoon",
  "Viking wars ",
  "Virtual Villagers: Orgins",
  "Void Tyrants",
  "Wallify wallpaper",
  "Warriors of the Universe",
  "Warship attack 3D ",
  "Watch out zombies",
  "Water Sort Puzzle",
  "WWE Immortals",
  "Warhammer 40,000 Freeblade",
  "Weed farm tycoon ganja paradise ",
  "Weekend Warriors MMA",
  "Where's my Water 2",
  "Wild things: animal adventure",
  "Wild west survival: zombie shooter",
  "Wings of steel",
  "Worldofsteel ",
  "World War 1944 ",
  "Worms 3",
  "Wrestling Revolution",
  "Wrestling Revolution 3D",
  "Xrecorder",
  "Zen idle",
  "Zombie Forest HD Survival ",
  "Zombie Hell 4",
  "Zombieland Double Tapper",
];

const fetchData = async () => {
  const cleanAppIds = [];
  for (const appName of appNames) {
    console.log(appName);
    try {
      const foundApp = (await gplay.search({ term: appName }))[0];
      if (foundApp) {
        cleanAppIds.push(foundApp.appId);
      } else {
        console.error("App not found: ", appName);
      }
      await new Promise((f) => setTimeout(f, 1000));
    } catch (e) {
      console.error("App not found: ", appName);
      console.error(e);
    }
  }

  const result = {};

  for (const id in cleanAppIds) {
    result[cleanAppIds[id]] = {
      category: "unclear-iap",
      features: ["unclear-iap"],
    };
  }

  console.log(result);
};

fetchData();
