import gplay from "google-play-scraper";
const appNames = [
  "Hungry Shark Evolution",
  "Smash Cops Heat",
  " Deadly Fight : Fighting Game",
  "Monster Defender",
  " Robbery Bob 2: Double Trouble",
  "Just Shout",
  "Tiny Troopers 2: Special Ops",
  "Street Fighting 2: Multiplayer ",
  "Stunt Car Racing – Multiplayer ",
  "Zombie Squad",
  "Age of wind 3",
  "Zombie Highway 2 ",
  "Can Knockdown 3",
  " Tank ON 2 – Jeep Hunter",
  "Chhota Bheem : The Hero",
  "Dictator 2 ",
  "ROBOTS",
  "Brothers: Clash of Fighters",
  " Farm Away! – Idle Farming",
  "Unfinished Mission ",
  "Gun Strike 2 ",
  "Build Away! -Idle City Builder",
  "The Factory",
  "Bio Inc. – Biomedical Game",
  "Mad Day – Truck Distance Game ",
  "Watch out Zombies! ",
  "Fruit Ninja Free",
  " Invention City",
  "Cricket Hungama 2016",
  " Zombie’s Got a Pogo",
  "Bee Brilliant",
  "Zombie Catchers ",
  " Watch out Zombies!",
  "Puzzle Craft 2",
  "The Factory",
  "Unfinished Mission",
  "Robots ",
  "Gun Strike 2",
  "Farm Away! – Idle Farming",
  "Route Z",
  "Cricket Hungama 2016",
  "Swamp Attack",
  "Hunger Games: Panem Run",
  "Zombie Catchers",
  "Watchout Zombies!",
  "Under Heroes – Clicker Game",
  "Last Heroes",
  "Biomedical Game",
  "Fruit Ninja Free",
  "On the Run",
  "Build Away! – Idle City Builder",
  "Invention City",
  "Brothers: Clash of Fighters",
  "The Factory",
  "Mad Day – Truck Distance Game",
  "Bee Brilliant",
  "Zombie’s Got a Pogo",
  "Dictator 2",
  "Sky Charms",
  "Storm the Train",
  "Monster Defender",
  "Smash Cope Heat",
  "Just Shout",
  "Tiny Troopers 2: Special Ops",
  "Robbery Bob 2: Double Trouble",
  "Bloons TD Battles",
  "Deadly Fight: Fighting Game",
  "Hungry Shark Evolution",
  "Injustice: Gods Among Us",
  "Tower Madness 2: 3D Defense",
  "Hero Simulator: idle Adventure",
  "Street Fighting 2: Multiplayer",
  "Hill Climb Racing",
  "Lunar Rescue Mission",
  "PROJECT : OFFROAD",
  "Project : Drift",
  "FROM THE SEA",
  "Soda Dungeon",
  "#DRIVE",
  "Psebay",
  "ReversEstory",
  "Tiny Rails",
  "ROBOTS",
  "Colour Switch",
  "Moto Delight",
  "DOKDO",
  "Nautical Life",
  "Space Life",
  "Fishing Life",
  "Idle Skilling",
  "Corin",
  "Alto",
  "Bid Wars: Pawn Empire",
  "Big Hunter",
  "Blades Away",
  "Blocky Farm Racing",
  "Dead Shell",
  "Event Horizon - Frontier",
  "dungeoning",
  "Drive and Park",
  "Dungeon Cards",
  "Carpet Bombing",
  "Cart Stunt Races",
  "Conduct THIS!",
  "Assassin",
  "Blendoku 2",
  "Alchemy",
  "Alchemy 2",
  "DevTycoon 2",
  "Hill Dash",
  "Endurance",
  "Idle Mechanics",
  "Idle Mine RPG",
  "Mr Bullet",
  "Idle Pocket Crafter",
  "Make It Rain",
  "Magic Rampage",
  "Odyssey",
  "Lapse",
  "Last Hope TD",
  "Line Driver",
  "MagnetBlock",
  "Mini TD 2",
  "Missile Escape",
  "Moto X3M",
  "Merge Magic",
  "Dragon World",
  "Mergeland",
  "Godus",
  "Tiny Tower",
];
const fetchData = async () => {
  const cleanAppIds = [];
  for (const appName of appNames) {
    console.log(appName);
    try {
      const foundApp = (await gplay.search({ term: appName }))[0];
      if (foundApp) {
        cleanAppIds.push(foundApp.appId);
      } else {
        console.error("App not found: ", appName);
      }
      await new Promise((f) => setTimeout(f, 1000));
    } catch (e) {
      console.error("App not found: ", appName);
      console.error(e);
    }
  }
  const result = {};
  for (const id in cleanAppIds) {
    result[cleanAppIds[id]] = {
      category: "unclear-iap",
      features: ["unclear-iap"],
    };
  }
  console.log(result);
};
fetchData();
